### ISSUE TITLE
Issue with the prediction function

### ISSUE THREAD

**Issue by sauberf** [Shawn1993/cnn-text-classification-pytorch#10]
I've been playing with the CNN text classification lately, and it seems it trains fine, but when it comes to predictions I get this error:

`
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    label = train.predict(args.predict, cnn, text_field, label_field)
  File "train.py", line 88, in predict
    return label_feild.vocab.itos[predicted.data[0][0]+1]
TypeError: 'int' object has no attribute '__getitem__'
`

I changed the `return label_feild.vocab.itos[predicted.data[0][0]+1]` to `return label_feild.vocab.itos[predicted.data[0]+1]` and bypassed the error, but most predictions are not accurate now. Can you please let me know what I'm missing here.

**Comment by xinwen-cs** [comment]
I have the same issue,have you solve it?

**Comment by melki** [comment]
Hi,

I have the same issue. 

```Traceback (most recent call last):

File "./main.py", line 104, in <module>

label = train.predict(args.predict, cnn, text_field, label_field, args.cuda)

  File "/home/melki/recital/project/cnn-text-classification-pytorch/train.py", line 90, in predict

    return label_feild.vocab.itos[predicted.data[0][0]+1]

TypeError: 'int' object is not subscriptable

```

**Comment by saurabhbh21** [comment]
replace 
return label_feild.vocab.itos[predicted.data[0][0]+1] 
with
out = predicted.data.cpu().numpy()
return label_feild.vocab.itos[out[0]+1]
