### ISSUE TITLE
Pre-trained word embeddings

### ISSUE THREAD

**Issue by AngusGLChen** [Shawn1993/cnn-text-classification-pytorch#13]
Has the loading of pre-trained word embedding (i.e., the one trained from Google News) been included in the code?

**Comment by abhiML** [comment]
Hey @AngusGLChen did you find the answer to your question?

**Comment by Leonardo-Rocha** [comment]
@abhiML I don't think so.

**Comment by sarahwie** [comment]
@abhiML if you want to add them, add a line below [this one](https://github.com/Shawn1993/cnn-text-classification-pytorch/blob/502d9b0542f9397e52a3355cc3d7ac16be7cc5c7/model.py#L20): 
        `self.embed.weight.data = torch.Tensor(W).clone()`

where `W` is a numpy matrix of shape `VxD`, and make sure the embedding indexes align with the ones being used to encode the data.

**Comment by ll0ruc** [comment]
@AngusGLChen on the code, the author uses the random initialization word vector that comes with nn.Embedding. If you want to use your own pre-trained word vector,
self.embed.weight.data.copy_(weight_matrix)
where weight_matrix is your own word vector matrix.
