### ISSUE TITLE
l2 norm

### ISSUE THREAD

**Issue by dongfang91** [Shawn1993/cnn-text-classification-pytorch#14]
Is there any code showing the usage of l2 norm?

**Comment by Eric-Wallace** [comment]
Just add the l2 regularization to the optimizer line in train.py

**Comment by dongfang91** [comment]
Can you be more specific?  
optimizer = torch.optim.Adam(model.parameters(), lr=args.lr) 

This line? As an argument?

**Comment by dongfang91** [comment]
Already figured it out, it's the weight_decay in optimizer. Thanks!
