### ISSUE TITLE
prediction error

### ISSUE THREAD

**Issue by nitish116** [Shawn1993/cnn-text-classification-pytorch#15]
training seems to work fine , when I run "python main.py"

but when I ran predict "python main.py -predict="I feel bad" -snapshot="snapshot/2018-01-08_13-10-29/snapshot_steps9000.pt", it is giving me this error 

RuntimeError: Given input size: (1, 3, 128). Calculated output size: (1, 0, 1). Output size is too small.

I haven't made any changes to code

**Comment by ZhengfengRao** [comment]
the sentence you predicted is too short, please view README.md, is says:" your text should longer then the max kernel size. "
default kernel size is [3, 4, 5], so your sentence's length should not be less then 5 words.

**Comment by SevenMpp** [comment]
Sorry to disturb you. How do you solve the prediction problem? Do you need to load the training data each time?  Otherwise it will be reported : AttributeError: 'Field' object has no attribute 'vocab'
