### ISSUE TITLE
Embedding Static

### ISSUE THREAD

**Issue by ASoleimaniB** [Shawn1993/cnn-text-classification-pytorch#21]
I thing the way this code implements Static Embedding is wrong.  Am I right?
This code, uses x=variable(x) when wants to make the embedding static, while it should be something like: self.embed.weight.requires_grad=False

**Comment by skurzhanskyi** [comment]
Using `Variable` also works. You can check by yourself.

**Comment by Z-Jeff** [comment]
It seems that the word embedding are kept static during training.
How to make the embedding changeable in backpropagation?
