### ISSUE TITLE
序列长度

### ISSUE THREAD

**Issue by JunmeiHao** [Shawn1993/cnn-text-classification-pytorch#22]
请问您这个程序序列长度为什么是没有固定的呢？还是在什么地方固定了，不过我并没有发现，请指教，谢谢

**Comment by ll0ruc** [comment]
torchtext里面data.Iterator.splits()函数将训练验证数据集打包成bantch_size=64的块，每一个batch中的序列的长度依照该batch中64个句子的最大长度为基准，所以每个batchs的固定的序列长度不一
