### ISSUE TITLE
feature.data.t_(), target.data.sub_(1)

### ISSUE THREAD

**Issue by elenacliu** [Shawn1993/cnn-text-classification-pytorch#26]
I know ``feature.data.t_()`` transposes the matrix, but what does ``target.data.sub_(1)`` do? Is it also necessary if the label starts from 0?

**Comment by inkyusa** [comment]
Hope this help
https://github.com/inkyusa/cnn-text-classification-pytorch/commit/6dfefe7ae442d982d010969f4c1a7f1bd3125576

**Comment by elenacliu** [comment]
I don't know very precisely how Pytorch operates on tensors, but it seems that in torchtext if we build a vocab for label, it will start with an unk_token, neither 0 or '0'. So if we want the labels to start from 0, we should subtract one from them.

**Comment by elenacliu** [comment]
Thank you for your code!

在2020-06-03 15:58:34，Inkyunotifications@github.com写道：

Hope this help
inkyusa@6dfefe7
